### ISSUE TITLE
Eigen URL no longer exists

### ISSUE THREAD

**Issue by tansey** [mattjj/pyhsmm-autoregressive#17]
I think the relevant link you now want is to https://gitlab.com/libeigen/eigen/-/archive/3.2.10/eigen-3.2.10.tar.gz (the same major version as is in the setup.py now but a slightly newer minor version).

**Comment by jonahpearl** [comment]
...and also seems line 25 in `setup.py` should read `thedir = glob(join('deps', 'eigen-*'))[0]` as the package naming scheme seems to have changed.

**Comment by slinderman** [comment]
I think it’s safe to say this repo will no longer be updated. You may be interested in dynamax though: https://github.com/probml/dynamax

**Comment by jonahpearl** [comment]
Thanks! I'm happy just commenting for anyone else (or myself) coming back here in the future to get back-compatibility with old code.

**Comment by slinderman** [comment]
Much appreciated :)
