### ISSUE TITLE
No module named distributions

### ISSUE THREAD

**Issue by lishen** [mattjj/pyhsmm-autoregressive#6]
I'm having trouble running the `demo.py` under the examples folder. Apparently, there is a module missing. Here is the error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-55502c29a74b> in <module>()
      9 from pyhsmm.util.stats import whiten, cov
     10 
---> 11 import autoregressive.models as m
     12 import autoregressive.distributions as d

build/bdist.macosx-10.5-x86_64/egg/autoregressive/__init__.py in <module>()

ImportError: No module named distributions

Looks like there is no such file as `distributions.py` under the autoregressive package.

**Comment by mattjj** [comment]
I had forgotten to commit a file. Thanks!

**Comment by gulsunde** [comment]
It still does give an error.

**Comment by mattjj** [comment]
Are you using the git master version or a pypi (pip) version?

**Comment by gulsunde** [comment]
Pip

**Comment by gulsunde** [comment]
I also tried the other version
